# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

frSVD <- function(X, k, q = 5L) {
    .Call('_frSVD_frSVD', PACKAGE = 'frSVD', X, k, q)
}

